### ISSUE TITLE
Not able to locate Dependencies

### ISSUE THREAD

**Issue by alamsohelrana** [daileyet/SafaribooksonlineGetter4J#1]
Dear Team,

I'm not able to download the dependencies(i.e. 1. htmlunit-2.18 2. ofc2struts2-1.0-SNAPSHOT 3. utilities-1.0-SNAPSHOT)
maybe the maven does not support those jars.. Please help. I'm a novice here :-(

Here is the error I'm getting in Eclipse**[Could not calculate build plan: Plugin org.apache.maven.plugins:maven-resources-plugin:2.7 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.7
Plugin org.apache.maven.plugins:maven-resources-plugin:2.7 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.7]**

EDIT1: tried mvn from command line ..[ **mvn compile -X

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.847 s
[INFO] Finished at: 2016-11-24T23:46:08+05:30
[INFO] Final Memory: 4M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.7 or one of its
 dependencies could not be resolved: Failed to read artifact descriptor for org.
apache.maven.plugins:maven-resources-plugin:jar:2.7: Could not transfer artifact
 org.apache.maven.plugins:maven-resources-plugin:pom:2.7 from/to central (https:
//repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.mave
n.apache.org/151.101.20.215] failed: Connection timed out: connect -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugi
ns:maven-resources-plugin:2.7 or one of its dependencies could not be resolved:
Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-
plugin:jar:2.7

...................................................................................................................** ]

**Comment by daileyet** [comment]
Hello, @alamsohelrana 
Thanks for your response. This is not latest version for utilities-1.0-SNAPSHOT. 
We have update the new version for that. Please fetch update from this project, we have update the file pom.xml.

BTW,  maybe the project [webscheduler](https://github.com/daileyet/webscheduler) will be useful for you. In that project, we use this SafaribooksonlineGetter4J as lib.

Regards,
Dailey
